spring:
  application:
    name: minu-app

  datasource:
    url: postgresql://minu_db_user:jbxF0mLAgGdUfbpk7yds3h6JMzDHE4mR@dpg-d76dfvpaae7s73c2k4bg-a.ohio-postgres.render.com/minu_db
    username: minu_db_user
    password: jbxF0mLAgGdUfbpk7yds3h6JMzDHE4mR
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080
